# -*- coding: utf-8 -*-
"""fake_headline_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2fAkLBAuQEXMytyk8NnI3PIq4HefcHm
"""

import random

# Define subjects
subject = [
    "virat kohli",
    "shahrukh khan",
    "MS",
    "RCB",
    "Nirmala Sitharaman",
    "A group of monkeys",
    "a group of friend",
    "A group of pandas" # Added new subject
]

# Define actions
actions=[
    "launches",
    "cancels",
    "dances with",
    "eats",
    "orders",
    "celebrates",
    "organizes a flash mob with" # Added new action
]

# Define objects/places
places_or_things=[
    "at red fort",
    "in mumbai local train",
    "at ganga ghat",
    "during ipl match",
    "at india gate",
    "the city mayor" # Added new object
]

# Start the headline generation loop
while True:
  subject_choice = random.choice(subject)
  actions_choice = random.choice(actions)
  objects_choice = random.choice(places_or_things)

  headline= f" BREAKING NEWS : {subject_choice} {actions_choice} {objects_choice} "
  print("\n"+ headline)

  # user input
  user_input= input("\n DO YOU WANT ANOTHER HEADLINE?(YES/NO)").strip().lower()

  if user_input == "no":
      break

# print goodbye message
print("\n GOODBYE! SEE YOU AGAIN")